######################################################################
# Automatically generated by qmake (3.1) Wed Dec 18 22:57:12 2024
######################################################################

QT       += core gui widgets

TEMPLATE = app
TARGET = keylogger
INCLUDEPATH += .

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_UP_TO=0x060000 # disables all APIs deprecated in Qt 6.0.0 and earlier

# Input
SOURCES += \
    main.cpp \
    mainwindow.cpp \
    keylogger.cpp

HEADERS += \
    mainwindow.h \
    keylogger.h

LIBS += -framework ApplicationServices -framework Carbon -framework CoreFoundation

CONFIG += c++11
